### ISSUE TITLE
Authentication and authorization

### ISSUE THREAD

**Issue by ansarizafar** [Claviz/drayman#4]
Is there any example app/tutorial showing how to authenticate and authorize users?

**Comment by jansivans** [comment]
Hi!
There are no tutorials on this topic (yet), but I'll for sure write something about it.
Usually authentication/authorization is based on data/tokens stored inside local storage.
You can work with local storage using [Browser object](http://www.drayman.io/docs/components-in-depth/helpers/the-browser-object).
I have created example repo for you on how to do this - https://github.com/jansivans/drayman-local-storage-example.
This example shows how to work with Browser object and local storage:
![CleanShot 2021-11-18 at 13 41 20](https://user-images.githubusercontent.com/5667073/142409450-be705dc5-795a-40a5-9f5b-b066e05a234e.gif)
If you have any questions left, I am happy to answer.

**Comment by ansarizafar** [comment]
Thanks for the example but local storage is not secure. I want to use httpOnly cookie for authentication/authorization.
There should a way to initialize drayman instance on the server with an inject-able context for components and middlewares.

**Comment by jansivans** [comment]
That's not a problem.
You can change Browser commands in example to set/retrieve/remove a cookie.

**Comment by ansarizafar** [comment]
I need to set httpOnly cookie on the server. There is no need to access it in the browser.

**Comment by jansivans** [comment]
Do you mean httpOnly cookie flag?
Do I understand correctly that you want to set it for responses coming from server (like when user clicks a button a request is sent to the server and server responds with the httpOnly flag set)?

**Comment by ansarizafar** [comment]
yes. That's how cookie based authentication works and that's why I asked for a way to initialize drayman instance on the server to add middleware to the request pipeline.

**Comment by jansivans** [comment]
Great!
I'll add this feature.

**Comment by jansivans** [comment]
Please try `1.8.0` version.
I have added middleware support to the Server object.
You can read about it [here](http://www.drayman.io/docs/components-in-depth/helpers/the-server-object#using-middlewares-and-request-interceptors).

**Comment by ansarizafar** [comment]
Here are few suggestions.

Replace expressjs with https://github.com/lukeed/polka
Replace Websockets with https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events or https://braid.org/ to make application more scale able.
My recommendation for the api

```
const server = drayman(config) 

server.context.set('count', 10)

// server should also expose request object
server.context.set('incrment', ({server, args}) => {
const count = server.context.get('count') + 1
server.context.set('count', count)
return count
)

server.use(middleware)

server.start()

**Comment by jansivans** [comment]
Do you suggest these things because you just know that they are more scalable or you have encountered some performance problems with Drayman?
If the latter, feel free to open separate issues describing problems in detail with some code snippets or experiment details on how Drayman performs.
